import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/layout/header';
import Footer from './components/layout/footer';
import React from 'react';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'FDICPLAN',
  description: 'Generated by create next app',
};

import { ReactNode } from 'react';

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <Header />
        <main className="flex-grow">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
